#!/usr/bin/env python3
"""
Comprehensive Analysis Report Generator
=========================================
One-click full report: runs OAV, ROVA, ANOVA, PCA, volcano, flavor wheel,
and generates an interactive HTML report with all results embedded.

Usage:
  from tools.comprehensive_report import generate_report
  html_path = generate_report(df, output_path='report.html')
"""

import json
import os
import time
from datetime import datetime
from pathlib import Path
import numpy as np
import pandas as pd


def generate_report(df, output_dir=None, title='GC-MS Analysis Report'):
    """Run comprehensive analysis and generate interactive HTML report.

    Args:
        df: DataFrame with GC-MS data
        output_dir: output directory (default: output/reports/)
        title: report title

    Returns:
        Path to generated HTML report
    """
    if output_dir is None:
        output_dir = Path(__file__).parent.parent / 'output' / 'reports'
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    report_path = output_dir / f'gcms_report_{timestamp}.html'

    # Initialize report sections
    sections = []

    # Header
    sections.append(f"""
    <div style="text-align:center; padding:2rem; background:linear-gradient(135deg, #1a5276, #2980b9); color:white; border-radius:12px; margin-bottom:2rem;">
        <h1 style="font-size:2rem; margin:0;">{title}</h1>
        <p style="opacity:0.8; margin-top:0.5rem;">Generated {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
        <p style="opacity:0.7; font-size:0.9rem;">
            {len(df)} records · {df['compound'].nunique()} compounds · {df['sample'].nunique()} samples
        </p>
    </div>
    """)

    # 1. Data Summary
    sections.append(_section_summary(df))

    # 2. OAV Analysis
    try:
        from flavor_tools import calculate_oav, get_oav_summary
        oav_summary = get_oav_summary(df)
        sections.append(_section_oav(oav_summary, df))
    except Exception as e:
        sections.append(f'<div class="error">OAV: {e}</div>')

    # 3. ROVA Analysis
    try:
        from flavor_tools import calculate_rova, get_rova_summary
        rova_summary = get_rova_summary(df)
        sections.append(_section_rova(rova_summary))
    except Exception as e:
        sections.append(f'<div class="error">ROVA: {e}</div>')

    # 4. Statistical Tests
    if 'group' in df.columns and df['group'].nunique() >= 2:
        try:
            sections.append(_section_statistics(df))
        except Exception as e:
            sections.append(f'<div class="error">Statistics: {e}</div>')

    # 5. PCA
    try:
        sections.append(_section_pca(df))
    except Exception as e:
        sections.append(f'<div class="error">PCA: {e}</div>')

    # 6. Top Compounds Table
    sections.append(_section_top_compounds(df))

    # Build HTML
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<script src="https://cdn.plot.ly/plotly-2.32.0.min.js"></script>
<style>
    body {{ font-family: 'Segoe UI', system-ui, sans-serif; max-width: 1000px; margin: auto; padding: 2rem; background: #f8f9fa; color: #2c3e50; }}
    .section {{ background: white; border-radius: 12px; padding: 1.5rem; margin-bottom: 1.5rem; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }}
    .section h2 {{ color: #1a5276; border-bottom: 2px solid #e9ecef; padding-bottom: 0.5rem; margin-top: 0; }}
    .metric-grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; }}
    .metric {{ background: #f8f9fa; border-radius: 8px; padding: 1rem; text-align: center; }}
    .metric .value {{ font-size: 1.8rem; font-weight: bold; color: #1a5276; }}
    .metric .label {{ font-size: 0.8rem; color: #666; margin-top: 0.25rem; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 0.9rem; }}
    th {{ background: #1a5276; color: white; padding: 0.5rem; text-align: left; }}
    td {{ padding: 0.4rem 0.5rem; border-bottom: 1px solid #e9ecef; }}
    tr:nth-child(even) {{ background: #f8f9fa; }}
    .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: bold; }}
    .badge-dominant {{ background: #c0392b; color: white; }}
    .badge-significant {{ background: #e67e22; color: white; }}
    .badge-contributing {{ background: #2980b9; color: white; }}
    .chart {{ width: 100%; height: 400px; }}
    .error {{ color: #c0392b; font-style: italic; }}
    .footer {{ text-align: center; color: #999; font-size: 0.8rem; margin-top: 2rem; }}
</style>
</head>
<body>
{''.join(sections)}
<div class="footer">
    Generated by GC-MS AI Analyzer · Open Source (MIT) · github.com/Tina-atk-love/gcms-ai-analyzer
</div>
</body>
</html>"""

    report_path.write_text(html, encoding='utf-8')
    return report_path


def _section_summary(df):
    n_samples = df['sample'].nunique()
    n_compounds = df['compound'].nunique()
    n_groups = df['group'].nunique() if 'group' in df.columns else 1
    total_area = int(df['area'].sum()) if 'area' in df.columns else 0
    return f"""
    <div class="section">
        <h2>1. Data Summary</h2>
        <div class="metric-grid">
            <div class="metric"><div class="value">{n_samples}</div><div class="label">Samples</div></div>
            <div class="metric"><div class="value">{n_compounds}</div><div class="label">Compounds</div></div>
            <div class="metric"><div class="value">{n_groups}</div><div class="label">Groups</div></div>
            <div class="metric"><div class="value">{total_area:,.0f}</div><div class="label">Total Area</div></div>
        </div>
    </div>"""


def _section_oav(summary, df):
    top = summary.get('top_oav_overall', [])[:10]
    if not top:
        return '<div class="section"><h2>2. OAV Analysis</h2><p>No OAV data available.</p></div>'

    rows = ''
    for item in top:
        badge_class = f"badge-{item['impact']}" if item['impact'] in ('dominant','significant','contributing') else ''
        rows += f"""<tr>
            <td>{item['compound']}</td>
            <td>{item['mean_oav']:.1f}</td>
            <td><span class="badge {badge_class}">{item['impact']}</span></td>
        </tr>"""

    return f"""
    <div class="section">
        <h2>2. Odor Activity Values (OAV)</h2>
        <table>
            <tr><th>Compound</th><th>OAV</th><th>Impact</th></tr>
            {rows}
        </table>
    </div>"""


def _section_rova(summary):
    top = summary.get('top_rova_overall', [])[:10]
    if not top:
        return ''

    rows = ''
    for item in top:
        rows += f"""<tr>
            <td>{item['compound']}</td>
            <td>{item['mean_rova_pct']:.1f}%</td>
            <td>{item['cumulative_pct']:.1f}%</td>
            <td>{item['dominance']}</td>
        </tr>"""

    note = summary.get('dominance_note', '')
    return f"""
    <div class="section">
        <h2>3. Relative Odor Activity Values (ROVA)</h2>
        <p style="color:#1a5276; font-style:italic;">{note}</p>
        <table>
            <tr><th>Compound</th><th>ROVA %</th><th>Cumulative %</th><th>Dominance</th></tr>
            {rows}
        </table>
    </div>"""


def _section_statistics(df):
    from scipy.stats import ttest_ind, f_oneway

    groups = df['group'].unique()
    if len(groups) < 2:
        return ''

    pivot = df.pivot_table(values='area', index='compound', columns='sample', aggfunc='mean').fillna(0)

    # t-test between first two groups
    g1_cols = [c for c in pivot.columns if groups[0] in c]
    g2_cols = [c for c in pivot.columns if groups[1] in c]

    results = []
    for compound in pivot.index[:100]:
        try:
            v1 = pivot.loc[compound, g1_cols].values
            v2 = pivot.loc[compound, g2_cols].values
            if v1.std() > 0 and v2.std() > 0:
                t, p = ttest_ind(v1, v2)
                fc = v1.mean() / v2.mean() if v2.mean() > 0 else float('inf')
                results.append((compound, p, fc, t))
        except:
            pass

    results.sort(key=lambda x: x[1])
    sig = [r for r in results if r[1] < 0.05][:15]

    rows = ''
    for name, p, fc, t in sig:
        direction = '↑' if fc > 1 else '↓'
        rows += f"""<tr>
            <td>{name}</td>
            <td>{p:.4f}</td>
            <td>{fc:.2f} {direction}</td>
        </tr>"""

    return f"""
    <div class="section">
        <h2>4. Statistical Analysis</h2>
        <p>Top significantly different compounds ({groups[0]} vs {groups[1]}):</p>
        <table>
            <tr><th>Compound</th><th>p-value</th><th>Fold Change</th></tr>
            {rows}
        </table>
        <p style="color:#999; font-size:0.8rem;">t-test, p &lt; 0.05, n={len(sig)} significant compounds</p>
    </div>"""


def _section_pca(df):
    """Generate PCA plot data as embedded Plotly JSON."""
    try:
        from sklearn.decomposition import PCA
        from sklearn.preprocessing import StandardScaler

        pivot = df.pivot_table(values='area', index='sample', columns='compound', aggfunc='mean').fillna(0)
        if pivot.shape[0] < 3 or pivot.shape[1] < 3:
            return ''

        X = StandardScaler().fit_transform(pivot)
        pca = PCA(n_components=2)
        scores = pca.fit_transform(X)

        groups = df.groupby('sample')['group'].first().values if 'group' in df.columns else ['All'] * len(scores)

        # Build Plotly JSON for embedding
        pca_json = {
            'data': [],
            'layout': {
                'title': 'PCA Score Plot',
                'xaxis': {'title': f'PC1 ({pca.explained_variance_ratio_[0]:.1%})'},
                'yaxis': {'title': f'PC2 ({pca.explained_variance_ratio_[1]:.1%})'},
                'template': 'plotly_white',
                'height': 400,
            }
        }

        unique_groups = list(set(groups))
        colors = ['#c0392b', '#2980b9', '#27ae60', '#e67e22', '#8e44ad']
        for i, g in enumerate(unique_groups):
            mask = [x == g for x in groups]
            pca_json['data'].append({
                'x': scores[mask, 0].tolist(),
                'y': scores[mask, 1].tolist(),
                'type': 'scatter',
                'mode': 'markers',
                'name': str(g),
                'marker': {'size': 12, 'color': colors[i % len(colors)]},
            })

        import json as _json
        pca_str = _json.dumps(pca_json)

        return f"""
        <div class="section">
            <h2>5. PCA Analysis</h2>
            <div id="pca_chart" class="chart"></div>
            <script>
                Plotly.newPlot('pca_chart', {pca_str}.data, {pca_str}.layout);
            </script>
        </div>"""
    except Exception:
        return ''


def _section_top_compounds(df):
    """Top 20 compounds by mean area."""
    top = df.groupby('compound')['area'].mean().sort_values(ascending=False).head(20)
    rows = ''
    for i, (name, area) in enumerate(top.items()):
        rows += f'<tr><td>{i+1}</td><td>{name}</td><td>{area:,.0f}</td></tr>'

    return f"""
    <div class="section">
        <h2>6. Top Compounds by Area</h2>
        <table>
            <tr><th>#</th><th>Compound</th><th>Mean Area</th></tr>
            {rows}
        </table>
    </div>"""


if __name__ == '__main__':
    from tools.demo_data import generate_demo_dataset
    df = generate_demo_dataset()
    path = generate_report(df)
    print(f'Report generated: {path}')
